### PR TITLE
Change to automatically rebuild views on error

### LINKED ISSUE #32: Error: past end:649935989-2097188320 < 650704372
On starting Patchbay, I get the following error. No new messages are appearing and most old messages aren't rendering. All messages in the `/gatherings` section just say 'Loading'. No user icons load.

I'm unable to use this feed, I'm resyncing now but will keep this feed for bug fixing purposes, depending on what you guys think.

@mixmix @dominictarr any thoughts? Looks to me like the sequencing is off somehow, though how it happened I've no idea. I've not done anything particularly special.

```
Error: view stream error
    at /shared/Projects/patchbay/node_modules/flumedb/index.js:139:35
    at /shared/Projects/patchbay/node_modules/pull-stream/sinks/drain.js:20:24
    at /shared/Projects/patchbay/node_modules/pull-stream/throughs/async-map.js:28:19
    at /shared/Projects/patchbay/node_modules/pull-cursor/skip.js:12:26
    at /shared/Projects/patchbay/node_modules/pull-cursor/cursor.js:28:28
    at /shared/Projects/patchbay/node_modules/flumelog-offset/inject.js:42:22
    at /shared/Projects/patchbay/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at Object.read (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:49:14)
  Error: past end:649935989-2097188320 < 650704372
    at Object.read (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:49:17)
    at next (/shared/Projects/patchbay/node_modules/flumelog-offset/frame/recoverable.js:47:16)
    at /shared/Projects/patchbay/node_modules/flumelog-offset/frame/recoverable.js:43:11
    at /shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:95:11
    at get (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:92:9)
    at /shared/Projects/patchbay/node_modules/flumelog-offset/frame/recoverable.js:41:16
    at Array.<anonymous> (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:95:11)
    at /shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:39:16
    at /shared/Projects/patchbay/node_modules/aligned-block-file/file.js:46:13
```

### PR DESCRIPTION
**Pull request by christianbundy**
Previously FlumeDB would handle errors by retrying the view build
operation, which would usually fail recursively until it hit the maximum
stack size. This behavior meant that "delete your views" was a common
fix, which is difficult for beginners and error-prone for everyone.
Running `rm -rf` in your database directory is scary.

This commit changes the behavior so that errors while building views
will trigger a rebuild instead of recursively retrying the build. This
gives FlumeDB the ability to self-heal when a Flumeview becomes corrupt,
but (as always) is a trade-off. Some errors are probably harmless or
will resolve themselves without manual intervention, but FlumeDB
shouldn't be responsible for enumerating the possible error states of
each Flumeview. Each Flumeview should maintain responsibility for its
own error states.

For example, if two instances of Flumeview-Level try to use the same
directory, we can expect the second instance to throw an error because
the first has locked the directory. If FlumeDB asks the second instance
to rebuild, it should throw a rebuild error and refuse to write to the
locked directory. As long as Flumeviews continue to refuse rebuilds when
manual intervention is unnecessary I think this change will be a big
improvement with a low risk of problematic behavior.

Resolves #32, or at least applies a general workaround for this class of bugs.

### CODE REVIEW

**Comment by dominictarr** [comment]
If you are gonna do this, it should be:

``` js
  sv.destroy(function () { build(-1) })
```
because you are telling flume the view is empty (`-1`) but maybe the view isn't really empty. You might just rewrite all the records currently in the view into it again, which may or may not produce the same effect. `ssb-friends` would end up the same but a reduce view that counted the number of records (or average size etc) wouldn't.

**Comment by dominictarr** [comment]
but, yeah, I think destroying and rebuilding is a good plan here

**Comment by christianbundy** [comment]
Thanks! Just pushed a commit to resolve that.

File: index.js [hunk 1]
```diff
@@ -135,9 +135,12 @@ module.exports = function (log, isReady, mapper) {
               Looper,
               sv.createSink(function (err) {
                 if(!flume.closed) {
-                  if(err)
-                    console.error(explain(err, 'view stream error, from:'+name))
-                  sv.since.once(build)
+                  if (err) {
+                    console.error(explain(err, `rebuilding ${name} after view stream error`))
+                    sv.destroy(() => build(-1))
```
Comment (mixmix) [inline index.js]: I've not seen this error so not sure this is the perfect place for this. BUT, it seems reasonable?

My main comment would be that there are two places now with this magic function 

```js
                    sv.destroy(() => build(-1))
```

I would like to see that defined as a function, like 
```js
function resetView () {
  sv.destroy(() => build(-1))
}
```

because then we have a clear place where we can name, comment + maintain this seeminlgy vital piece of code

**Comment by mixmix** [comment]
I wonder if we should start a `flumeview.debug.log` (a name so bad anyone can make it better). This way we can append data for future reference about who rebuild the index, what the error was, perhaps which identity triggered it?

I know this makes more work, but I think without it, we've got a magical fix which might lead to problems which are very hard to debug?

**Comment by mixmix** [comment]
I've got a home-roled format we should use for the debug log. It's like JSON but more _bespoke_ and you know, better.

File: index.js (hunk 1 above)
Comment (christianbundy) [reply index.js]: Will do, thanks.

**Comment by christianbundy** [comment]
> I know this makes more work, but I think without it, we've got a magical fix which might lead to problems which are very hard to debug?

Yeah, this only solves the problem of having to tell people "please `rm -rf` your views". I don't think I have the energy to add that feature to this patch, unfortunately.

File: index.js (hunk 1 above)
Comment (christianbundy) [reply index.js]: Done!

**Comment by mixmix** [comment]
fair enough. Can you please then leave a big ol COMMENT like 

```
// TODO
// log this error to a debug.log, so that we know if it's happening
```

File: .gitignore [hunk 2]
```diff
@@ -0,0 +1 @@
+node_modules
```
Comment (mixmix) [inline .gitignore]: :heart:

**Comment by mixmix** [comment]
hey @christianbundy I'm giving this a :+1: (ready to merge)

However, I need a review on a fix I just posted to your last commit - I think you accidentally changed the behaviour. Looked like tired coding, so just posted up fix, and added comment I requested

**Comment by christianbundy** [comment]
Oh no, that was a super bad patch -- thanks for fixing it up! :heart: I shouldn't code before bed.
